optimize_structured:
  description: >
    STRICT OUTPUT REQUIRED (JSON ONLY).

    You MUST use the manufacturing_cost_calculator tool for ALL cost calculations.

    Given machines {machines} and demand {product_demand}:
    1. Produce a JSON object with exactly these keys: "strategy_name", "machine_allocations".
       - "machine_allocations" must be a dict mapping machine keys to integer production units.
       - The sum of values in "machine_allocations" MUST be >= {product_demand}.
    2. After producing the allocation JSON, call manufacturing_cost_calculator with that allocation and return its results.

    DO NOT include any explanatory text outside the JSON block. DO NOT calculate costs yourself.
  expected_output: >
    JSON object: {"strategy_name": "...", "machine_allocations": {"Tool_X": 1000, ...}}

evaluate_allocation:
  description: >
    You MUST use the brute_force_optimizer tool to find the optimal solution. You should also use the manufacturing_cost_calculator to verify costs.

    Given the problem with machines {machines} and demand {product_demand}:
    
    1. First, call the brute_force_optimizer tool with the machines and demand to find the mathematically optimal allocation.
    2. Use the manufacturing_cost_calculator to verify the costs of the allocator's solution from the previous task.
    3. Compare the allocator's solution (from the previous task) to the optimal solution you found.
    4. Provide detailed feedback on:
       - Cost difference between the allocator's solution and optimal solution
       - Efficiency analysis (percentage difference)
       - Specific recommendations for improvement
       - What the allocator did well and what it could do better
    
    You MUST use the brute_force_optimizer tool. Also use manufacturing_cost_calculator to verify the allocator's costs.
    
    The previous task result will be available in the context.
  expected_output: >
    Detailed evaluation report comparing the allocator's solution to the optimal solution, including cost verification and specific recommendations for improvement.